/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tpi2025.view.VeterinarioViews;

import com.mycompany.tpi2025.view.BuscarView;
import com.mycompany.tpi2025.view.CrearDiagnosticoView;
import com.mycompany.tpi2025.view.CrearGatoView;
import com.mycompany.tpi2025.view.JPanels.DatosPrincipalesPanelView;
import com.mycompany.tpi2025.view.VerHistorialGatoView;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;

/**
 *
 * @author aquin
 */
public class VeterinarioPrincipalView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VeterinarioPrincipalView.class.getName());
    private final CardLayout cl;
    private final Map<PanelesVeterinario, JPanel> paneles = new HashMap<>();

    public VeterinarioPrincipalView() {
        initComponents();

        cl = (CardLayout) contenedor.getLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        tpM = new javax.swing.JMenu();
        miPerfilMI = new javax.swing.JMenuItem();
        cerrarSesionMI = new javax.swing.JMenuItem();
        cerrarMI = new javax.swing.JMenuItem();
        famM = new javax.swing.JMenu();
        emitirAptitudFamiliaMI = new javax.swing.JMenuItem();
        hogarM = new javax.swing.JMenu();
        emitirAptitudHogarMI = new javax.swing.JMenuItem();
        gatoHistorialMI = new javax.swing.JMenu();
        modificarGatoMI = new javax.swing.JMenuItem();
        historialMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TPI");
        setResizable(false);

        contenedor.setLayout(new java.awt.CardLayout());

        tpM.setText("TP");

        miPerfilMI.setText("Mi Perfil");
        tpM.add(miPerfilMI);

        cerrarSesionMI.setText("Cerrar Sesion");
        tpM.add(cerrarSesionMI);

        cerrarMI.setText("Cerrar Programa");
        cerrarMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarMIActionPerformed(evt);
            }
        });
        tpM.add(cerrarMI);

        menuBar.add(tpM);

        famM.setText("Familia");

        emitirAptitudFamiliaMI.setText("Emitir Aptitud");
        famM.add(emitirAptitudFamiliaMI);

        menuBar.add(famM);

        hogarM.setText("Hogares");

        emitirAptitudHogarMI.setText("Emitir Aptitud");
        hogarM.add(emitirAptitudHogarMI);

        menuBar.add(hogarM);

        gatoHistorialMI.setText("Gatos");

        modificarGatoMI.setText("Ver/Modificar/Eliminar");
        gatoHistorialMI.add(modificarGatoMI);

        historialMI.setText("Historial");
        gatoHistorialMI.add(historialMI);

        menuBar.add(gatoHistorialMI);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarMIActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VeterinarioPrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarMI;
    private javax.swing.JMenuItem cerrarSesionMI;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuItem emitirAptitudFamiliaMI;
    private javax.swing.JMenuItem emitirAptitudHogarMI;
    private javax.swing.JMenu famM;
    private javax.swing.JMenu gatoHistorialMI;
    private javax.swing.JMenuItem historialMI;
    private javax.swing.JMenu hogarM;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miPerfilMI;
    private javax.swing.JMenuItem modificarGatoMI;
    private javax.swing.JMenu tpM;
    // End of variables declaration//GEN-END:variables

    public void cargarDatosPrincipales(String titulo, String nombre, String telefono, String nombreUsuario) {
        DatosPrincipalesPanelView panel = getPanel(PanelesVeterinario.DATOS_PRINCIPALES, DatosPrincipalesPanelView.class);
        panel.setTitulo(titulo);
        panel.setNombre(nombre);
        panel.setTelefono(telefono);
        panel.setUsuario(nombreUsuario);
    }

    public void setMiPerfilListener(ActionListener listener) {
        miPerfilMI.addActionListener(listener);
    }
    public void setCerrarAplicacionListener(ActionListener listener) {
        cerrarMI.addActionListener(listener);
    }

    public void setCerrarSesionListener(ActionListener listener) {
        cerrarSesionMI.addActionListener(listener);
    }
    
    public void setHistorialGatoListener(ActionListener l) {
        historialMI.addActionListener(l);
    }
    public void setModificarGatoListener(ActionListener l) {
        modificarGatoMI.addActionListener(l);
    }
    
    //EMISION CERTIFICADO DE APTITUD
    
    public void setEmitirAptitudFamiliaListener(ActionListener l) {
        emitirAptitudFamiliaMI.addActionListener(l);
    }
    public void setEmitirAptitudHogarListener(ActionListener l) {
        emitirAptitudHogarMI.addActionListener(l);
    }
    
    //GESTION DE PANELES

    public void mostrarPanel(PanelesVeterinario identificador) {
        JPanel vista = paneles.get(identificador);

        if (vista == null) {
            vista = crearPanel(identificador);
            if (vista != null) {
                paneles.put(identificador, vista);
                contenedor.add(vista, identificador.getTexto());
            } else {
                return;
            }
        }

        cl.show(contenedor, identificador.getTexto());
    }

    private JPanel crearPanel(PanelesVeterinario identificador) {
        return switch (identificador) {
            case VER_HISTORIAL -> new VerHistorialGatoView();
            case CREAR_DIAGNOSTICO, VER_DIAGNOSTICO -> new CrearDiagnosticoView();
            case BUSCAR_FAMILIA_APTITUD, BUSCAR_HOGAR_APTITUD -> new BuscarView();
            case MODIFICAR_GATO -> new CrearGatoView();
            default -> null;
        };
    }

    public <N extends JPanel> N getPanel(PanelesVeterinario identificador, Class<N> tipo) {
        JPanel panel = paneles.get(identificador);
        if (panel == null) {
            return null;
        }
        if (tipo.isInstance(panel)) {
            return tipo.cast(panel);
        }
        throw new IllegalArgumentException("El panel no es del tipo esperado: " + tipo.getSimpleName());
    }
}
