/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tpi2025.view.VoluntarioViews;

import com.mycompany.tpi2025.view.JPanels.AMUsuarioView;
import com.mycompany.tpi2025.view.JPanels.BuscarView;
import com.mycompany.tpi2025.view.JPanels.CrearGatoView;
import com.mycompany.tpi2025.view.JPanels.DatosPrincipalesPanelView;
import com.mycompany.tpi2025.view.JPanels.PostulacionView;
import com.mycompany.tpi2025.view.JPanels.TareaRealizadaView;
import com.mycompany.tpi2025.view.JPanels.VerPostulacionFamiliaView;
import com.mycompany.tpi2025.view.JPanels.VerPostulacionHogarView;
import com.mycompany.tpi2025.view.JPanels.VisitaSeguimientoView;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;

/**
 *
 * @author aquin
 */
public class VoluntarioPrincipalView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VoluntarioPrincipalView.class.getName());
    private final CardLayout cl;
    private final Map<PanelesVoluntario, JPanel> paneles = new HashMap<>();

    public VoluntarioPrincipalView() {
        initComponents();

        cl = (CardLayout) contenedor.getLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        tpM = new javax.swing.JMenu();
        miPerfilMI = new javax.swing.JMenuItem();
        cerrarSesionMI = new javax.swing.JMenuItem();
        cerrarMI = new javax.swing.JMenuItem();
        volM = new javax.swing.JMenu();
        tareaRealizadaMI = new javax.swing.JMenuItem();
        registrarVisitaMI = new javax.swing.JMenuItem();
        famM = new javax.swing.JMenu();
        asignacionFamiliaMI = new javax.swing.JMenuItem();
        hogarM = new javax.swing.JMenu();
        asignacionHogarMI = new javax.swing.JMenuItem();
        gatoHistorialMI = new javax.swing.JMenu();
        crearGatoMI = new javax.swing.JMenuItem();
        modificarGatoMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TPI");
        setResizable(false);

        contenedor.setLayout(new java.awt.CardLayout());

        tpM.setText("TP");

        miPerfilMI.setText("Mi Perfil");
        tpM.add(miPerfilMI);

        cerrarSesionMI.setText("Cerrar Sesion");
        tpM.add(cerrarSesionMI);

        cerrarMI.setText("Cerrar Programa");
        cerrarMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarMIActionPerformed(evt);
            }
        });
        tpM.add(cerrarMI);

        menuBar.add(tpM);

        volM.setText("Voluntarios");

        tareaRealizadaMI.setText("Tarea Realizada");
        volM.add(tareaRealizadaMI);

        registrarVisitaMI.setText("Registrar Visita");
        volM.add(registrarVisitaMI);

        menuBar.add(volM);

        famM.setText("Familia");

        asignacionFamiliaMI.setText("Asignar a Familia");
        famM.add(asignacionFamiliaMI);

        menuBar.add(famM);

        hogarM.setText("Hogares");

        asignacionHogarMI.setText("Asignar a Hogar");
        hogarM.add(asignacionHogarMI);

        menuBar.add(hogarM);

        gatoHistorialMI.setText("Gatos");

        crearGatoMI.setText("Crear");
        gatoHistorialMI.add(crearGatoMI);

        modificarGatoMI.setText("Ver/Modificar/Eliminar");
        gatoHistorialMI.add(modificarGatoMI);

        menuBar.add(gatoHistorialMI);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarMIActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VoluntarioPrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem asignacionFamiliaMI;
    private javax.swing.JMenuItem asignacionHogarMI;
    private javax.swing.JMenuItem cerrarMI;
    private javax.swing.JMenuItem cerrarSesionMI;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuItem crearGatoMI;
    private javax.swing.JMenu famM;
    private javax.swing.JMenu gatoHistorialMI;
    private javax.swing.JMenu hogarM;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miPerfilMI;
    private javax.swing.JMenuItem modificarGatoMI;
    private javax.swing.JMenuItem registrarVisitaMI;
    private javax.swing.JMenuItem tareaRealizadaMI;
    private javax.swing.JMenu tpM;
    private javax.swing.JMenu volM;
    // End of variables declaration//GEN-END:variables

    public void cargarDatosPrincipales(String titulo, String nombre, String telefono, String nombreUsuario) {
        DatosPrincipalesPanelView panel = getPanel(PanelesVoluntario.DATOS_PRINCIPALES, DatosPrincipalesPanelView.class);
        panel.setTitulo(titulo);
        panel.setNombre(nombre);
        panel.setTelefono(telefono);
        panel.setUsuario(nombreUsuario);
    }

    public void setMiPerfilListener(ActionListener listener) {
        miPerfilMI.addActionListener(listener);
    }

    public void setCerrarAplicacionListener(ActionListener listener) {
        cerrarMI.addActionListener(listener);
    }

    public void setCerrarSesionListener(ActionListener listener) {
        cerrarSesionMI.addActionListener(listener);
    }
    //ASIGNACION

    public void setAsignacionFamiliaListener(ActionListener l) {
        asignacionFamiliaMI.addActionListener(l);
    }

    public void setAsignacionHogarListener(ActionListener l) {
        asignacionHogarMI.addActionListener(l);
    }

    //TAREA REALIZADA
    public void setTareaRealizadaListener(ActionListener l) {
        tareaRealizadaMI.addActionListener(l);
    }

    public void setVisitaListener(ActionListener l) {
        registrarVisitaMI.addActionListener(l);
    }

    public void setCrearGatoListener(ActionListener l) {
        crearGatoMI.addActionListener(l);
    }

    public void setModificarGatoListener(ActionListener l) {
        modificarGatoMI.addActionListener(l);
    }

    //GESTION DE PANELES
    public void mostrarPanel(PanelesVoluntario identificador) {
        JPanel vista = paneles.get(identificador);

        if (vista == null) {
            vista = crearPanel(identificador);
            if (vista != null) {
                paneles.put(identificador, vista);
                contenedor.add(vista, identificador.getTexto());
            } else {
                return;
            }
        }

        cl.show(contenedor, identificador.getTexto());
    }

    private JPanel crearPanel(PanelesVoluntario identificador) {
        return switch (identificador) {
            case DATOS_PRINCIPALES ->
                new DatosPrincipalesPanelView();
            case MI_PERFIL ->
                new AMUsuarioView();
            case CREAR_GATO, MODIFICAR_GATO ->
                new CrearGatoView();
            case POSTULARSE ->
                new PostulacionView();
            case ASIGNAR_GATO_FAMILIA ->
                new VerPostulacionFamiliaView();
            case ASIGNAR_GATO_HOGAR ->
                new VerPostulacionHogarView();
            case BUSCAR_VOLUNTARIO_TAREA_REALIZADA, BUSCAR_FAMILIA_ASIGNACION, BUSCAR_HOGAR_ASIGNACION ->
                new BuscarView();
            case TAREA_REALIZADA ->
                new TareaRealizadaView();
            case VISITA ->
                new VisitaSeguimientoView();
            default ->
                null;
        };
    }

    public <N extends JPanel> N getPanel(PanelesVoluntario identificador, Class<N> tipo) {
        JPanel panel = paneles.get(identificador);
        if (panel == null) {
            return null;
        }
        if (tipo.isInstance(panel)) {
            return tipo.cast(panel);
        }
        throw new IllegalArgumentException("El panel no es del tipo esperado: " + tipo.getSimpleName());
    }
}
