/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.tpi2025.view.VoluntarioViews;

import com.mycompany.tpi2025.view.LoginView;
import java.awt.CardLayout;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author aquin
 */
public class VoluntarioPrincipalView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VoluntarioPrincipalView.class.getName());
    private final CardLayout cl;
    private LoginView login;
    /** Creates new form PrincipalView */
    public VoluntarioPrincipalView() {
        initComponents();
        
        cl = (CardLayout) contenedor.getLayout();
        
        //como panel principal mostramos el login
        mostrarLoginView();
        
        JMenu tpMenu = new JMenu("TP");
        JMenuItem salirProgramaItem = new JMenuItem("Salir");
        JMenuItem cerrarSesionProgramaItem = new JMenuItem("Cerrar Sesion");
        tpMenu.add(salirProgramaItem);
        tpMenu.add(cerrarSesionProgramaItem);
        menuBar.add(tpMenu);
        
        
        
    }
    
    private void mostrarLoginView(){
        //se verifica que no se haya creado el panel
        if(login == null){
            login = new LoginView();
            contenedor.add(login,"LOGIN");
        }
        //muestra el panel
        cl.show(contenedor, "LOGIN");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TPI");
        setResizable(false);

        contenedor.setLayout(new java.awt.CardLayout());
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VoluntarioPrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    
}
