/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tpi2025.view;

import com.mycompany.tpi2025.controller.DatosTabla;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aquin
 */
public class BuscarView extends javax.swing.JPanel {

    /**
     * Creates new form CrearVoluntarioView
     */
    public BuscarView() {
        initComponents();
        activarAccion(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accionBtn = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buscarUsuarioTf = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();

        accionBtn.setText("-");
        accionBtn.setEnabled(false);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(tablaDatos);
        tablaDatos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        titulo.setText("-");

        jLabel1.setText("Buscar usuario");

        buscarBtn.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accionBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(titulo)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buscarUsuarioTf, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buscarBtn))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarUsuarioTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(accionBtn)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accionBtn;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField buscarUsuarioTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

//    public void setAccionListener(ActionListener listener) {
//        accionBtn.addActionListener(listener);
//    }
    
    public void setAccionListener(ActionListener l) {
        for (ActionListener al : accionBtn.getActionListeners()) {
            accionBtn.removeActionListener(al);
        }
        accionBtn.addActionListener(l);
    }

    public void setBuscarListener(ActionListener listener) {
        buscarBtn.addActionListener(listener);
    }
    
    public void setSeleccionTablaListener(ListSelectionListener listener){
        this.tablaDatos.getSelectionModel().addListSelectionListener(listener);
    }

    public JTable getTablaDatos() {
        return tablaDatos;
    }

    public void resaltarFila(int fila) {
        // -1 porque si no se encuentra el articulo con el nombre insertado devuelve -1
        if (fila != -1) {
            tablaDatos.setRowSelectionInterval(fila, fila);
            tablaDatos.scrollRectToVisible(tablaDatos.getCellRect(fila, 0, true));
        }
    }

    public void setTitulo(String titulo) {
        this.titulo.setText(titulo);
    }

    public void setAccionTexto(String texto) {
        this.accionBtn.setText(texto);
    }

    public <T extends DatosTabla> void reloadTable(List<T> elementos, String[] encabezados) {
        DefaultTableModel model = new DefaultTableModel(encabezados, 0);

        for (T elem : elementos) {
            model.addRow(elem.obtenerDatos());
        }

        tablaDatos.setModel(model);
    }

    public String getBuscarUsuarioTf() {
        return buscarUsuarioTf.getText();
    }

    public void setBuscarUsuarioTf(String buscarUsuarioTf) {
        this.buscarUsuarioTf.setText(buscarUsuarioTf);
    }
    
    public void mostrarMensaje(String titulo,String texto, int tipoMensaje){
        JOptionPane.showMessageDialog(this, texto,titulo,tipoMensaje);
    }
    
    public int obtenerIndiceFila(){
        return tablaDatos.getSelectedRow();
    }
    
    public String obtenerValorTabla(int fila, int columna){
        return tablaDatos.getValueAt(fila, columna).toString();
    }
    
    public void activarAccion(boolean valor){
        accionBtn.setEnabled(valor);
    }
}
