/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tpi2025.view.JPanels;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author aquin
 */
public class TareaRealizadaView extends javax.swing.JPanel {

    /**
     * Creates new form TareaRealizadaView
     */
    public TareaRealizadaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tareaRealizada = new javax.swing.JComboBox<>();
        ubicacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        registrarBtn = new javax.swing.JButton();

        tareaRealizada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentación", "Captura para castración", "Control veretinario", "Transporte a hogar transitorio" }));

        jLabel1.setText("Tarea");

        jLabel2.setText("Ubicación");

        titulo.setText("-");

        registrarBtn.setText("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(tareaRealizada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ubicacion)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarBtn)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tareaRealizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(registrarBtn)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JComboBox<String> tareaRealizada;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField ubicacion;
    // End of variables declaration//GEN-END:variables

    public String getTareaRealizada() {
        return tareaRealizada.getSelectedItem().toString();
    }

    public String getUbicacion() {
        return ubicacion.getText();
    }

    public void setTitulo(String titulo) {
        this.titulo.setText(titulo);
    }

    public void setRegistrarListener(ActionListener l){
        registrarBtn.addActionListener(l);
    }
    
    public void mostrarErrorMensaje(String m){
        JOptionPane.showMessageDialog(this, m,"Error",JOptionPane.ERROR_MESSAGE);
    }
    public void mostrarInfoMensaje(String m){
        JOptionPane.showMessageDialog(this, m,"Informacion",JOptionPane.INFORMATION_MESSAGE);
    }

}
