/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tpi2025.view.JPanels;

import com.mycompany.tpi2025.model.Postulacion;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aquin
 */
public class VerPostulacionFamiliaView extends javax.swing.JPanel {

    /**
     * Creates new form VerPostulacionFamiliaView
     */
    public VerPostulacionFamiliaView() {
        initComponents();
        activarAsignacion(false);
        //System.out.println("view.........------------------------------------------------------------------------");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        asignarBtn = new javax.swing.JButton();

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro Postulacion", "ID Gato", "Postulante"
            }
        ));
        tablaDatos.setColumnSelectionAllowed(true);
        tablaDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaDatos);
        tablaDatos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        titulo.setText("-");

        asignarBtn.setText("Asignar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(asignarBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titulo)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(asignarBtn)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    public void setSeleccionListaListener(ListSelectionListener l){
        tablaDatos.getSelectionModel().addListSelectionListener(l);
    }
    
    public void setAsignarListener(ActionListener l){
        asignarBtn.addActionListener(l);
    }
    
    
    public void resaltarFila(int fila) {
        // -1 porque si no se encuentra el articulo con el nombre insertado devuelve -1
        if (fila != -1) {
            tablaDatos.setRowSelectionInterval(fila, fila);
            tablaDatos.scrollRectToVisible(tablaDatos.getCellRect(fila, 0, true));
        }
    }
    
    public void reloadTable(List<Postulacion> elementos) {
        DefaultTableModel model = (DefaultTableModel) tablaDatos.getModel();
        model.setRowCount(0);
        for (Postulacion elem : elementos) {
            model.addRow(new Object[]{elem.getId(),elem.getIdGato(),elem.getPostulante()});
        }
        //System.out.println("MM22-------------------------------------------");
        tablaDatos.setModel(model);
        //System.out.println("MM223-------------------------------------------");
    }
    
    public int obtenerIndiceFila(){
        return tablaDatos.getSelectedRow();
    }
    
    public String obtenerValorTabla(int fila, int columna){
        return tablaDatos.getValueAt(fila, columna).toString();
    }
    
    public void activarAsignacion(boolean valor){
        asignarBtn.setEnabled(valor);
    }
    
    public void setTitulo(String texto){
        titulo.setText(texto);
    }
}
