/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp4.pa2.view.articulos;

import com.mycompany.tp4.pa2.view.articulos.jpanels.ElectricidadDomiciliariaPanel;
import com.mycompany.tp4.pa2.view.articulos.jpanels.ElectricidadIndustrialPanel;
import com.mycompany.tp4.pa2.view.articulos.jpanels.HerramientaPanel;
import java.awt.CardLayout;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author aquin
 */
public class CrearArticuloView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearArticuloView.class.getName());
    private CardLayout cl;
    private ElectricidadIndustrialPanel indu;
    private ElectricidadDomiciliariaPanel domi;
    private HerramientaPanel herra;
    /**
     * Creates new form CrearArticuloView
     */
    public CrearArticuloView() {
        initComponents();
        
        
        cl = (CardLayout) principalPanel.getLayout();
        indu = new ElectricidadIndustrialPanel();
        domi = new ElectricidadDomiciliariaPanel();
        herra = new HerramientaPanel();
        
        
        principalPanel.add(indu,"Electricidad Industrial");
        principalPanel.add(domi,"Electricidad Domiciliaria");
        principalPanel.add(herra,"Herramienta");
        
        cl.show(principalPanel, "Electricidad Industrial");
    }
    
    public void setPanel(String tipo){
        cl.show(principalPanel, tipo);
    }
    
    public JComboBox<String> getTipoArticuloCombo() {
        return tipoArticuloCombo;
    }

    public void setTipoArticuloCombo(ComboBoxModel<String> model) {
        this.tipoArticuloCombo.setModel(model);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoArticuloCombo = new javax.swing.JComboBox<>();
        principalPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreArticuloTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        atrasBtn = new javax.swing.JButton();
        guardarArticuloBtn = new javax.swing.JButton();
        precioSp = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creación de Artículo");
        setResizable(false);

        jLabel1.setText("Tipo de Artículo");

        principalPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        atrasBtn.setText("Atrás");

        guardarArticuloBtn.setText("Guardar");

        precioSp.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        javax.swing.GroupLayout bgJPanelLayout = new javax.swing.GroupLayout(bgJPanel);
        bgJPanel.setLayout(bgJPanelLayout);
        bgJPanelLayout.setHorizontalGroup(
            bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(bgJPanelLayout.createSequentialGroup()
                        .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tipoArticuloCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreArticuloTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioSp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(atrasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarArticuloBtn)
                .addGap(20, 20, 20))
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bgJPanelLayout.setVerticalGroup(
            bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreArticuloTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoArticuloCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atrasBtn)
                    .addComponent(guardarArticuloBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearArticuloView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JPanel bgJPanel;
    private javax.swing.JButton guardarArticuloBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombreArticuloTf;
    private javax.swing.JSpinner precioSp;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JComboBox<String> tipoArticuloCombo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getAtrasBtn() {
        return atrasBtn;
    }

    public javax.swing.JButton getGuardarArticuloBtn() {
        return guardarArticuloBtn;
    }

    public javax.swing.JSpinner getPrecioSp() {
        return precioSp;
    }

    public javax.swing.JTextField getNombreArticuloTf() {
        return nombreArticuloTf;
    }

    public ElectricidadDomiciliariaPanel getDomi() {
        return domi;
    }

    public HerramientaPanel getHerra() {
        return herra;
    }

    public ElectricidadIndustrialPanel getIndu() {
        return indu;
    }
}