/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp4.pa2.view.articulos;

import com.mycompany.tp4.pa2.view.articulos.jpanels.ElectricidadDomiciliariaPanel;
import com.mycompany.tp4.pa2.view.articulos.jpanels.ElectricidadIndustrialPanel;
import com.mycompany.tp4.pa2.view.articulos.jpanels.HerramientaPanel;
import java.awt.CardLayout;
import javax.swing.ComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/**
 *
 * @author aquin
 */
public class EditarArticuloView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarArticuloView.class.getName());
    private CardLayout cl;
    private ElectricidadIndustrialPanel indu;
    private ElectricidadDomiciliariaPanel domi;
    private HerramientaPanel herra;
    /**
     * Creates new form EditarArticuloView
     */
    public EditarArticuloView() {
        initComponents();
        
        cl = (CardLayout) principalPanel.getLayout();
        indu = new ElectricidadIndustrialPanel();
        domi = new ElectricidadDomiciliariaPanel();
        herra = new HerramientaPanel();
        
        
        principalPanel.add(indu,"Electricidad Industrial");
        principalPanel.add(domi,"Electricidad Domiciliaria");
        principalPanel.add(herra,"Herramienta");
        
        cl.show(principalPanel, "Electricidad Industrial");
    }

    public void setTipoArticuloTf(String tipoArticuloTf) {
        this.tipoArticuloTf.setText(tipoArticuloTf);
    }
    
    public void setPanel(String tipo){
        cl.show(principalPanel, tipo);
    }
    
    public javax.swing.JButton getAtrasBtn() {
        return atrasBtn;
    }

    public javax.swing.JButton getGuardarArticuloBtn() {
        return guardarArticuloBtn;
    }

    public javax.swing.JSpinner getPrecioSp() {
        return precioSp;
    }

    public ElectricidadDomiciliariaPanel getDomi() {
        return domi;
    }

    public HerramientaPanel getHerra() {
        return herra;
    }

    public ElectricidadIndustrialPanel getIndu() {
        return indu;
    }

    public JButton getBuscarBtn() {
        return buscarBtn;
    }

    public void setNombreArtBuscarTf(String nombreArtBuscarTf) {
        this.nombreArtBuscarTf.setText(nombreArtBuscarTf);
    }

    public JTextField getNombreArtBuscarTf() {
        return nombreArtBuscarTf;
    }

    public JTable getTablaDatos() {
        return tablaDatos;
    }
    
    public void setNombreArticuloTf(String nombreArticuloTf) {
        this.nombreArticuloTf.setText(nombreArticuloTf);
    }

    public void setPrecioSp(double precioSp) {
        this.precioSp.setValue(precioSp);
    }

    public void setTablaDatos(TableModel dataModel){
        this.tablaDatos.setModel(dataModel);
    }
    
    public javax.swing.JTextField getTipoArticuloTf() {
        return tipoArticuloTf;
    }
    
    public void resaltarFila(int fila) {
        // -1 porque si no se encuentra el articulo con el nombre insertado devuelve -1
        if (fila != -1) {
            tablaDatos.setRowSelectionInterval(fila, fila);
            tablaDatos.scrollRectToVisible(tablaDatos.getCellRect(fila, 0, true));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        principalPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreArticuloTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        guardarArticuloBtn = new javax.swing.JButton();
        precioSp = new javax.swing.JSpinner();
        tipoArticuloTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        nombreArtBuscarTf = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edición de Artículo");
        setResizable(false);

        bgJPanel.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tipo de Artículo");

        principalPanel.setBackground(new java.awt.Color(255, 255, 255));
        principalPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        nombreArticuloTf.setEditable(false);
        nombreArticuloTf.setBackground(new java.awt.Color(204, 204, 204));
        nombreArticuloTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Precio");

        guardarArticuloBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        guardarArticuloBtn.setText("Guardar");

        precioSp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        precioSp.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        tipoArticuloTf.setEditable(false);
        tipoArticuloTf.setBackground(new java.awt.Color(204, 204, 204));
        tipoArticuloTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Edición");

        javax.swing.GroupLayout bgJPanelLayout = new javax.swing.GroupLayout(bgJPanel);
        bgJPanel.setLayout(bgJPanelLayout);
        bgJPanelLayout.setHorizontalGroup(
            bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarArticuloBtn)
                .addGap(43, 43, 43))
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgJPanelLayout.createSequentialGroup()
                        .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(bgJPanelLayout.createSequentialGroup()
                                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tipoArticuloTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreArticuloTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioSp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addContainerGap(49, Short.MAX_VALUE))))
            .addComponent(principalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgJPanelLayout.setVerticalGroup(
            bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreArticuloTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoArticuloTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(guardarArticuloBtn)
                .addGap(30, 30, 30))
        );

        jPanel1.setBackground(java.awt.Color.white);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nombre del artículo");

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tablaDatos);

        nombreArtBuscarTf.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        nombreArtBuscarTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        buscarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscarBtn.setText("Buscar");

        atrasBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atrasBtn.setText("Atrás");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atrasBtn)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreArtBuscarTf, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(buscarBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarBtn)
                    .addComponent(nombreArtBuscarTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(atrasBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bgJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarArticuloView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JPanel bgJPanel;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JButton guardarArticuloBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField nombreArtBuscarTf;
    private javax.swing.JTextField nombreArticuloTf;
    private javax.swing.JSpinner precioSp;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField tipoArticuloTf;
    // End of variables declaration//GEN-END:variables

   

    
}
