/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package com.mycompany.tpi2025.model.enums;

/**
 *
 * @author aquin
 */
public enum Permiso {
    REGISTRAR_GATO,
    REGISTRAR_TAREA_REALIZADA,
    ASIGNAR_QR,
    ASIGNAR_GATO_FAMILA,
    REGISTRAR_VISITA_SEGUIMIENTO,
    VER_PUNTOS_AVISTAMIENTO,
    VER_ZONAS_GATOS,
    ACTUALIZAR_ESTADO_GATO,
    VER_REPUTACION_FAMILIA,
    VER_HISTORIAL_MEDICO_GATO,
    ACTUALIZAR_DIAGNOSTICO_GATO,
    ACTUALIZAR_TRATAMIENTO,
    SUBIR_ESTUDIO,
    EMITIR_CERTIFICADO_ADPTITUD,
    REGISTRAR_FAMILIA,
    VER_GATOS_DISPONIBLES,
    POSTULARSE_ADOPCION,
    VER_MAPA,
    MODIFICAR_ZONA,
    ANIADIR_ZONA,
    ELIMINAR_ZONA,
    REGISTRAR_VETERINARIO,
    REGISTRAR_HOGAR,
    REGISTRAR_VOLUNTARIO,
    ELIMINAR_HOGAR,
    ELIMINAR_GATO,
    ELIMINAR_VOLUNTARIO,
    ELIMINAR_FAMILIA,
    ELIMINAR_VETERINARIO,
    GENERAR_REPORTE,
    MODIFICAR_DATOS_FAMILIA,
    MODIFICAR_DATOS_HOGAR,
    MODIFICAR_DATOS_VETERINARIO,
    MEDIFICAR_DATOS_VOLUNTARIO,
    ANIADIR_PUNTO_AVISTAMIENTO,
    TODO,
    MODIFICAR_REPUTACION_FAMILIA
}
