/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.tpi2025.view.AdministradorViews;

import com.mycompany.tpi2025.view.CrearUsuarioView;
import com.mycompany.tpi2025.view.JPanels.DatosPrincipalesPanelView;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JPanel;

/**
 *
 * @author aquin
 */
public class AdministradorPrincipalView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdministradorPrincipalView.class.getName());
    private final CardLayout cl;
    private final Map<String, JPanel> paneles = new HashMap<>();
//    private DatosPrincipalesPanelView datosPrincipales;
//    private CrearUsuarioView crearAdmin;
//    private CrearUsuarioView crearVet;
//    private CrearUsuarioView crearVol;
//    private CrearUsuarioView crearFam;
//    private CrearUsuarioView crearHog;
    /** Creates new form PrincipalView */
    public AdministradorPrincipalView() {
        initComponents();
        
        cl = (CardLayout) contenedor.getLayout();
        
        //como panel principal mostramos el login
        //mostrarLoginView();
        
//        JMenu tpMenu = new JMenu("TP");
//        JMenuItem salirProgramaItem = new JMenuItem("Salir");
//        JMenuItem cerrarSesionProgramaItem = new JMenuItem("Cerrar Sesion");
//        tpMenu.add(salirProgramaItem);
//        tpMenu.add(cerrarSesionProgramaItem);
//        menuBar.add(tpMenu);
        
        
        
    }
    
//    private void mostrarLoginView(){
//        //se verifica que no se haya creado el panel
//        if(login == null){
//            login = new LoginView();
//            contenedor.add(login,"LOGIN");
//        }
//        //muestra el panel
//        cl.show(contenedor, "LOGIN");
//    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        tpM = new javax.swing.JMenu();
        cerrarSesionMI = new javax.swing.JMenuItem();
        cerrarMI = new javax.swing.JMenuItem();
        adminM = new javax.swing.JMenu();
        crearAdminMI = new javax.swing.JMenuItem();
        vetM = new javax.swing.JMenu();
        crearVetMI = new javax.swing.JMenuItem();
        famM = new javax.swing.JMenu();
        crearFamMI = new javax.swing.JMenuItem();
        volM = new javax.swing.JMenu();
        crearVolMI = new javax.swing.JMenuItem();
        hogarM = new javax.swing.JMenu();
        crearHogarMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TPI");
        setResizable(false);

        contenedor.setLayout(new java.awt.CardLayout());

        tpM.setText("TP");

        cerrarSesionMI.setText("Cerrar Sesion");
        tpM.add(cerrarSesionMI);

        cerrarMI.setText("Cerrar Programa");
        cerrarMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarMIActionPerformed(evt);
            }
        });
        tpM.add(cerrarMI);

        menuBar.add(tpM);

        adminM.setText("Administradores");

        crearAdminMI.setText("Crear");
        adminM.add(crearAdminMI);

        menuBar.add(adminM);

        vetM.setText("Veterinarios");

        crearVetMI.setText("Crear");
        vetM.add(crearVetMI);

        menuBar.add(vetM);

        famM.setText("Familias");

        crearFamMI.setText("Crear");
        famM.add(crearFamMI);

        menuBar.add(famM);

        volM.setText("Voluntarios");

        crearVolMI.setText("Crear");
        volM.add(crearVolMI);

        menuBar.add(volM);

        hogarM.setText("Hogar");

        crearHogarMI.setText("Crear");
        hogarM.add(crearHogarMI);

        menuBar.add(hogarM);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarMIActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdministradorPrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminM;
    private javax.swing.JMenuItem cerrarMI;
    private javax.swing.JMenuItem cerrarSesionMI;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuItem crearAdminMI;
    private javax.swing.JMenuItem crearFamMI;
    private javax.swing.JMenuItem crearHogarMI;
    private javax.swing.JMenuItem crearVetMI;
    private javax.swing.JMenuItem crearVolMI;
    private javax.swing.JMenu famM;
    private javax.swing.JMenu hogarM;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu tpM;
    private javax.swing.JMenu vetM;
    private javax.swing.JMenu volM;
    // End of variables declaration//GEN-END:variables

    
    public void cargarDatosPrincipales(String titulo,String nombre, String telefono, String nombreUsuario){
        DatosPrincipalesPanelView panel = getPanel("DATOS_PRINCIPALES", DatosPrincipalesPanelView.class);
        panel.setTitulo(titulo);
        panel.setNombre(nombre);
        panel.setTelefono(telefono);
        panel.setUsuario(nombreUsuario);
    }
    
    public void setCerrarAplicacionListener(ActionListener listener){
        cerrarMI.addActionListener(listener);
    }
    public void setCerrarSesionListener(ActionListener listener){
        cerrarSesionMI.addActionListener(listener);
    }
    public void setCrearAdminListener(ActionListener listener){
        crearAdminMI.addActionListener(listener);
    }
    
    public void setCrearVetListener(ActionListener l){
        crearVetMI.addActionListener(l);
    }
    public void setCrearVolListener(ActionListener l){
        crearVolMI.addActionListener(l);
    }
    public void setCrearFamListener(ActionListener l){
        crearFamMI.addActionListener(l);
    }
    public void setCrearHogarListener(ActionListener l){
        crearHogarMI.addActionListener(l);
    }

//    public DatosPrincipalesPanelView getDatosPrincipales() {
//        return datosPrincipales;
//    }
//    
//    public void setDatosPrincipales(DatosPrincipalesPanelView view){
//        datosPrincipales = view;
//    }
//
//    public CrearUsuarioView getCrearAdmin() {
//        return crearAdmin;
//    }
//    
//    public void setCrearAdmin(CrearUsuarioView view){
//        this.crearAdmin = view;
//    }
    
    // public <T extends JPanel> T mostrarPanel(T vista,String identificador,Class<T> tipo){
    //     if(vista == null){
    //         try {
    //             vista = tipo.getDeclaredConstructor().newInstance();
    //             contenedor.add(vista,identificador);
    //         } catch (Exception ex) {
    //             System.out.println("ERROR MOSTRAR VISTA--------------------------------------");
    //         }
    //     }
    //     cl.show(contenedor,identificador);
    //     return vista;
    // }

    public void mostrarPanel(String identificador) {
        JPanel vista = paneles.get(identificador);

        if (vista == null) {
            vista = crearPanel(identificador);
            if (vista != null) {
                paneles.put(identificador, vista);
                contenedor.add(vista, identificador);
            } else {
                System.out.println("No se pudo crear el panel para: " + identificador);
                return;
            }
        }

        cl.show(contenedor, identificador);
    }

    private JPanel crearPanel(String identificador) {
        switch (identificador) {
            case "DATOS_PRINCIPALES":
                return new DatosPrincipalesPanelView();
                
            case "CREAR_ADMINISTRADOR":
            case "CREAR_FAMILIA":
            case "CREAR_VETERINARIO":
            case "CREAR_VOLUNTARIO":
            case "CREAR_HOGAR":
                return new CrearUsuarioView();

            default:
                return null;
        }
    }

    public <N extends JPanel> N getPanel(String identificador, Class<N> tipo) {
        JPanel panel = paneles.get(identificador);
        if (panel == null) return null;
        if (tipo.isInstance(panel)) {
            return tipo.cast(panel);
        }
        throw new IllegalArgumentException("El panel no es del tipo esperado: " + tipo.getSimpleName());
    }
}
