/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tpi2025.view.AdministradorViews;

import com.mycompany.tpi2025.controller.PanelesAdministrador;
import com.mycompany.tpi2025.view.AMUsuarioView;
import com.mycompany.tpi2025.view.BuscarView;
import com.mycompany.tpi2025.view.JPanels.DatosPrincipalesPanelView;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JPanel;

/**
 *
 * @author aquin
 */
public class AdministradorPrincipalView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdministradorPrincipalView.class.getName());
    private final CardLayout cl;
    private final Map<PanelesAdministrador, JPanel> paneles = new HashMap<>();

    public AdministradorPrincipalView() {
        initComponents();

        cl = (CardLayout) contenedor.getLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        tpM = new javax.swing.JMenu();
        cerrarSesionMI = new javax.swing.JMenuItem();
        cerrarMI = new javax.swing.JMenuItem();
        adminM = new javax.swing.JMenu();
        crearAdminMI = new javax.swing.JMenuItem();
        eliminarAdminMI = new javax.swing.JMenuItem();
        buscarAdminMI = new javax.swing.JMenuItem();
        modificarAdminMI = new javax.swing.JMenuItem();
        vetM = new javax.swing.JMenu();
        crearVetMI = new javax.swing.JMenuItem();
        eliminarVetMI = new javax.swing.JMenuItem();
        buscarVetMI = new javax.swing.JMenuItem();
        modificarVetMI = new javax.swing.JMenuItem();
        famM = new javax.swing.JMenu();
        crearFamMI = new javax.swing.JMenuItem();
        eliminarFamMI = new javax.swing.JMenuItem();
        buscarFamMI = new javax.swing.JMenuItem();
        modificarFamMI = new javax.swing.JMenuItem();
        volM = new javax.swing.JMenu();
        crearVolMI = new javax.swing.JMenuItem();
        eliminarVolMI = new javax.swing.JMenuItem();
        buscarVolMI = new javax.swing.JMenuItem();
        modificarVolMI = new javax.swing.JMenuItem();
        hogarM = new javax.swing.JMenu();
        crearHogarMI = new javax.swing.JMenuItem();
        eliminarHogarMI = new javax.swing.JMenuItem();
        buscarHogarMI = new javax.swing.JMenuItem();
        modificarHogarMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TPI");
        setResizable(false);

        contenedor.setLayout(new java.awt.CardLayout());

        tpM.setText("TP");

        cerrarSesionMI.setText("Cerrar Sesion");
        tpM.add(cerrarSesionMI);

        cerrarMI.setText("Cerrar Programa");
        cerrarMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarMIActionPerformed(evt);
            }
        });
        tpM.add(cerrarMI);

        menuBar.add(tpM);

        adminM.setText("Administradores");

        crearAdminMI.setText("Crear");
        adminM.add(crearAdminMI);

        eliminarAdminMI.setText("Eliminar");
        adminM.add(eliminarAdminMI);

        buscarAdminMI.setText("Buscar");
        adminM.add(buscarAdminMI);

        modificarAdminMI.setText("Modificar");
        adminM.add(modificarAdminMI);

        menuBar.add(adminM);

        vetM.setText("Veterinarios");

        crearVetMI.setText("Crear");
        vetM.add(crearVetMI);

        eliminarVetMI.setText("Eliminar");
        vetM.add(eliminarVetMI);

        buscarVetMI.setText("Buscar");
        vetM.add(buscarVetMI);

        modificarVetMI.setText("Modificar");
        vetM.add(modificarVetMI);

        menuBar.add(vetM);

        famM.setText("Familia");

        crearFamMI.setText("Crear");
        famM.add(crearFamMI);

        eliminarFamMI.setText("Eliminar");
        famM.add(eliminarFamMI);

        buscarFamMI.setText("Buscar");
        famM.add(buscarFamMI);

        modificarFamMI.setText("Modificar");
        famM.add(modificarFamMI);

        menuBar.add(famM);

        volM.setText("Voluntarios");

        crearVolMI.setText("Crear");
        volM.add(crearVolMI);

        eliminarVolMI.setText("Eliminar");
        volM.add(eliminarVolMI);

        buscarVolMI.setText("Buscar");
        volM.add(buscarVolMI);

        modificarVolMI.setText("Modificar");
        volM.add(modificarVolMI);

        menuBar.add(volM);

        hogarM.setText("Hogar");

        crearHogarMI.setText("Crear");
        hogarM.add(crearHogarMI);

        eliminarHogarMI.setText("Eliminar");
        hogarM.add(eliminarHogarMI);

        buscarHogarMI.setText("Buscar");
        hogarM.add(buscarHogarMI);

        modificarHogarMI.setText("Modificar");
        hogarM.add(modificarHogarMI);

        menuBar.add(hogarM);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarMIActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdministradorPrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminM;
    private javax.swing.JMenuItem buscarAdminMI;
    private javax.swing.JMenuItem buscarFamMI;
    private javax.swing.JMenuItem buscarHogarMI;
    private javax.swing.JMenuItem buscarVetMI;
    private javax.swing.JMenuItem buscarVolMI;
    private javax.swing.JMenuItem cerrarMI;
    private javax.swing.JMenuItem cerrarSesionMI;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuItem crearAdminMI;
    private javax.swing.JMenuItem crearFamMI;
    private javax.swing.JMenuItem crearHogarMI;
    private javax.swing.JMenuItem crearVetMI;
    private javax.swing.JMenuItem crearVolMI;
    private javax.swing.JMenuItem eliminarAdminMI;
    private javax.swing.JMenuItem eliminarFamMI;
    private javax.swing.JMenuItem eliminarHogarMI;
    private javax.swing.JMenuItem eliminarVetMI;
    private javax.swing.JMenuItem eliminarVolMI;
    private javax.swing.JMenu famM;
    private javax.swing.JMenu hogarM;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem modificarAdminMI;
    private javax.swing.JMenuItem modificarFamMI;
    private javax.swing.JMenuItem modificarHogarMI;
    private javax.swing.JMenuItem modificarVetMI;
    private javax.swing.JMenuItem modificarVolMI;
    private javax.swing.JMenu tpM;
    private javax.swing.JMenu vetM;
    private javax.swing.JMenu volM;
    // End of variables declaration//GEN-END:variables

    public void cargarDatosPrincipales(String titulo, String nombre, String telefono, String nombreUsuario) {
        DatosPrincipalesPanelView panel = getPanel(PanelesAdministrador.DATOS_PRINCIPALES, DatosPrincipalesPanelView.class);
        panel.setTitulo(titulo);
        panel.setNombre(nombre);
        panel.setTelefono(telefono);
        panel.setUsuario(nombreUsuario);
    }

    public void setCerrarAplicacionListener(ActionListener listener) {
        cerrarMI.addActionListener(listener);
    }

    public void setCerrarSesionListener(ActionListener listener) {
        cerrarSesionMI.addActionListener(listener);
    }
    
    //CREACION
    
    public void setCrearAdminListener(ActionListener listener) {
        crearAdminMI.addActionListener(listener);
    }

    public void setCrearVetListener(ActionListener l) {
        crearVetMI.addActionListener(l);
    }

    public void setCrearVolListener(ActionListener l) {
        crearVolMI.addActionListener(l);
    }

    public void setCrearFamListener(ActionListener l) {
        crearFamMI.addActionListener(l);
    }

    public void setCrearHogarListener(ActionListener l) {
        crearHogarMI.addActionListener(l);
    }
    
    //ELIMINAR
    
    public void setEliminarAdminListener(ActionListener listener) {
        eliminarAdminMI.addActionListener(listener);
    }

    public void setEliminarVetListener(ActionListener l) {
        eliminarVetMI.addActionListener(l);
    }

    public void setEliminarVolListener(ActionListener l) {
        eliminarVolMI.addActionListener(l);
    }

    public void setEliminarFamListener(ActionListener l) {
        eliminarFamMI.addActionListener(l);
    }

    public void setEliminarHogarListener(ActionListener l) {
        eliminarHogarMI.addActionListener(l);
    }
    
    //BUSCAR
    
    public void setBuscarAdminListener(ActionListener listener) {
        buscarAdminMI.addActionListener(listener);
    }

    public void setBuscarVetListener(ActionListener l) {
        buscarVetMI.addActionListener(l);
    }

    public void setBuscarVolListener(ActionListener l) {
        buscarVolMI.addActionListener(l);
    }

    public void setBuscarFamListener(ActionListener l) {
        buscarFamMI.addActionListener(l);
    }

    public void setBuscarHogarListener(ActionListener l) {
        buscarHogarMI.addActionListener(l);
    }
    
    //MODIFICAR
    
    public void setModificarAdminListener(ActionListener listener) {
        modificarAdminMI.addActionListener(listener);
    }

    public void setModificarVetListener(ActionListener l) {
        modificarVetMI.addActionListener(l);
    }

    public void setModificarVolListener(ActionListener l) {
        modificarVolMI.addActionListener(l);
    }

    public void setModificarFamListener(ActionListener l) {
        modificarFamMI.addActionListener(l);
    }

    public void setModificarHogarListener(ActionListener l) {
        modificarHogarMI.addActionListener(l);
    }
    
    //GESTION DE PANELES

    public void mostrarPanel(PanelesAdministrador identificador) {
        JPanel vista = paneles.get(identificador);

        if (vista == null) {
            vista = crearPanel(identificador);
            if (vista != null) {
                paneles.put(identificador, vista);
                contenedor.add(vista, identificador.getTexto());
            } else {
                System.out.println("No se pudo crear el panel para: " + identificador.getTexto());
                return;
            }
        }

        cl.show(contenedor, identificador.getTexto());
    }

    private JPanel crearPanel(PanelesAdministrador identificador) {
        return switch (identificador) {
            case DATOS_PRINCIPALES -> new DatosPrincipalesPanelView();
            case CREAR_ADMINISTRADOR, CREAR_FAMILIA, CREAR_VETERINARIO, CREAR_VOLUNTARIO, CREAR_HOGAR,
                MODIFICAR_ADMINISTRADOR, MODIFICAR_FAMILIA, MODIFICAR_VETERINARIO, MODIFICAR_VOLUNTARIO, MODIFICAR_HOGAR -> new AMUsuarioView();
            case BUSCAR_ADMINISTRADOR, BUSCAR_FAMILIA, BUSCAR_VETERINARIO, BUSCAR_VOLUNTARIO, BUSCAR_HOGAR,
                ELIMINAR_ADMINISTRADOR, ELIMINAR_FAMILIA, ELIMINAR_VETERINARIO, ELIMINAR_VOLUNTARIO, ELIMINAR_HOGAR -> new BuscarView();
            default -> null;
        };
    }

    public <N extends JPanel> N getPanel(PanelesAdministrador identificador, Class<N> tipo) {
        JPanel panel = paneles.get(identificador);
        if (panel == null) {
            return null;
        }
        if (tipo.isInstance(panel)) {
            return tipo.cast(panel);
        }
        throw new IllegalArgumentException("El panel no es del tipo esperado: " + tipo.getSimpleName());
    }
}
