/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp4.pa2.view.facturas;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/**
 *
 * @author aquin
 */
public class CrearFacturaView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearFacturaView.class.getName());

    /**
     * Creates new form CrearFacturaView
     */
    public CrearFacturaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        seleccionClienteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreClienteTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dniClienteTf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        nombreArtBuscarTf = new javax.swing.JTextField();
        cantidadArticuloSp = new javax.swing.JSpinner();
        buscarBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();
        agregarArticuloBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosArticuloTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArticulosSeleccionados = new javax.swing.JTable();
        removerArticuloBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        precioTotalTf = new javax.swing.JTextField();
        crearFacturaBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tipoFacturaCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creación de Factura");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        seleccionClienteBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seleccionClienteBtn.setText("Seleccionar Cliente");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");

        nombreClienteTf.setEditable(false);
        nombreClienteTf.setBackground(new java.awt.Color(255, 255, 255));
        nombreClienteTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("DNI");

        dniClienteTf.setEditable(false);
        dniClienteTf.setBackground(new java.awt.Color(255, 255, 255));
        dniClienteTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre del artículo");

        tablaDatos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos.setEnabled(false);
        jScrollPane.setViewportView(tablaDatos);

        nombreArtBuscarTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreArtBuscarTf.setEnabled(false);

        cantidadArticuloSp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidadArticuloSp.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantidadArticuloSp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cantidadArticuloSp.setEnabled(false);

        buscarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.setEnabled(false);

        atrasBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atrasBtn.setText("Atrás");

        agregarArticuloBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agregarArticuloBtn.setText("Agregar -->");
        agregarArticuloBtn.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Cantidad");

        jScrollPane1.setBorder(null);

        datosArticuloTA.setEditable(false);
        datosArticuloTA.setColumns(20);
        datosArticuloTA.setLineWrap(true);
        datosArticuloTA.setRows(5);
        datosArticuloTA.setWrapStyleWord(true);
        datosArticuloTA.setAutoscrolls(false);
        datosArticuloTA.setBorder(null);
        datosArticuloTA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(datosArticuloTA);

        tablaArticulosSeleccionados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaArticulosSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artículos Seleccionados", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArticulosSeleccionados.setEnabled(false);
        jScrollPane2.setViewportView(tablaArticulosSeleccionados);
        if (tablaArticulosSeleccionados.getColumnModel().getColumnCount() > 0) {
            tablaArticulosSeleccionados.getColumnModel().getColumn(0).setResizable(false);
            tablaArticulosSeleccionados.getColumnModel().getColumn(1).setResizable(false);
            tablaArticulosSeleccionados.getColumnModel().getColumn(1).setPreferredWidth(1);
        }

        removerArticuloBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removerArticuloBtn.setText("Remover");
        removerArticuloBtn.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Total a pagar");

        precioTotalTf.setEditable(false);
        precioTotalTf.setBackground(new java.awt.Color(255, 255, 255));
        precioTotalTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        crearFacturaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        crearFacturaBtn.setText("Crear Factura");
        crearFacturaBtn.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(atrasBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearFacturaBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreArtBuscarTf, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agregarArticuloBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cantidadArticuloSp)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(24, 24, 24))
                                    .addComponent(removerArticuloBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(buscarBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(precioTotalTf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 150, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreArtBuscarTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioTotalTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadArticuloSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(agregarArticuloBtn)
                        .addGap(18, 18, 18)
                        .addComponent(removerArticuloBtn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atrasBtn)
                    .addComponent(crearFacturaBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tipo de Factura");

        tipoFacturaCb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipoFacturaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        tipoFacturaCb.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(seleccionClienteBtn)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nombreClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dniClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoFacturaCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionClienteBtn)
                    .addComponent(tipoFacturaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearFacturaView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarArticuloBtn;
    private javax.swing.JButton atrasBtn;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JSpinner cantidadArticuloSp;
    private javax.swing.JButton crearFacturaBtn;
    private javax.swing.JTextArea datosArticuloTA;
    private javax.swing.JTextField dniClienteTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreArtBuscarTf;
    private javax.swing.JTextField nombreClienteTf;
    private javax.swing.JTextField precioTotalTf;
    private javax.swing.JButton removerArticuloBtn;
    private javax.swing.JButton seleccionClienteBtn;
    private javax.swing.JTable tablaArticulosSeleccionados;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JComboBox<String> tipoFacturaCb;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getSeleccionClienteBtn() {
        return seleccionClienteBtn;
    }

    public void setNombreClienteTf(String nombreClienteTf) {
        this.nombreClienteTf.setText(nombreClienteTf);
    }

    public void setCantidadArticuloSp(int cantidadArticuloSp) {
        this.cantidadArticuloSp.setValue(cantidadArticuloSp);
    }

    public void setDniClienteTf(String dniClienteTf) {
        this.dniClienteTf.setText(dniClienteTf);
    }

    public void setPrecioTotalTf(String precioTotalTf) {
        this.precioTotalTf.setText(precioTotalTf);
    }

    public javax.swing.JButton getAgregarArticuloBtn() {
        return agregarArticuloBtn;
    }

    public javax.swing.JSpinner getCantidadArticuloSp() {
        return cantidadArticuloSp;
    }

    public javax.swing.JTable getTablaArticulosSeleccionados() {
        return tablaArticulosSeleccionados;
    }

    public javax.swing.JComboBox<String> getTipoFacturaCb() {
        return tipoFacturaCb;
    }

    public javax.swing.JButton getRemoverArticuloBtn() {
        return removerArticuloBtn;
    }
    
    
    
    public JButton getAtrasBtn() {
        return atrasBtn;
    }

    public JButton getBuscarBtn() {
        return buscarBtn;
    }

    public void setNombreArtBuscarTf(String nombreArtBuscarTf) {
        this.nombreArtBuscarTf.setText(nombreArtBuscarTf);
    }

    public JTextField getNombreArtBuscarTf() {
        return nombreArtBuscarTf;
    }

    public JTable getTablaDatos() {
        return tablaDatos;
    }

    public void setTablaDatos(TableModel dataModel){
        this.tablaDatos.setModel(dataModel);
    }
    
    public void setDatosArticuloTA(String datosArticuloTA) {
        this.datosArticuloTA.setText(datosArticuloTA);
    }
    
    public void resaltarFila(int fila) {
        // -1 porque si no se encuentra el articulo con el nombre insertado devuelve -1
        if (fila != -1) {
            tablaDatos.setRowSelectionInterval(fila, fila);
            tablaDatos.scrollRectToVisible(tablaDatos.getCellRect(fila, 0, true));
        }
    }
    
    public void habilitarContenido(boolean habilitado){
        nombreArtBuscarTf.setEnabled(habilitado);
        buscarBtn.setEnabled(habilitado);
        tablaDatos.setEnabled(habilitado);
        cantidadArticuloSp.setEnabled(habilitado);
        agregarArticuloBtn.setEnabled(habilitado);
        removerArticuloBtn.setEnabled(habilitado);
        tablaArticulosSeleccionados.setEnabled(habilitado);
        tipoFacturaCb.setEnabled(habilitado);
        crearFacturaBtn.setEnabled(habilitado);
    }

    public JButton getCrearFacturaBtn() {
        return crearFacturaBtn;
    }

    public void setTablaArticulosSeleccionados(TableModel dataModel) {
        this.tablaArticulosSeleccionados.setModel(dataModel);
    }
    
    
    
}
