/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package com.mycompany.tpi2025.controller.enums;

/**
 *
 * @author aquin
 */
public enum PanelesAdministrador {
    DATOS_PRINCIPALES("DATOS_PRINCIPALES"),

    // Administrador
    CREAR_ADMINISTRADOR("CREAR_ADMINISTRADOR"),
    BUSCAR_ADMINISTRADOR("BUSCAR_ADMINISTRADOR"),
    MODIFICAR_ADMINISTRADOR("MODIFICAR_ADMINISTRADOR"),
    ELIMINAR_ADMINISTRADOR("ELIMINAR_ADMINISTRADOR"),

    // Familia
    CREAR_FAMILIA("CREAR_FAMILIA"),
    BUSCAR_FAMILIA("BUSCAR_FAMILIA"),
    MODIFICAR_FAMILIA("MODIFICAR_FAMILIA"),
    ELIMINAR_FAMILIA("ELIMINAR_FAMILIA"),

    // Veterinario
    CREAR_VETERINARIO("CREAR_VETERINARIO"),
    BUSCAR_VETERINARIO("BUSCAR_VETERINARIO"),
    MODIFICAR_VETERINARIO("MODIFICAR_VETERINARIO"),
    ELIMINAR_VETERINARIO("ELIMINAR_VETERINARIO"),

    // Voluntario
    CREAR_VOLUNTARIO("CREAR_VOLUNTARIO"),
    BUSCAR_VOLUNTARIO("BUSCAR_VOLUNTARIO"),
    MODIFICAR_VOLUNTARIO("MODIFICAR_VOLUNTARIO"),
    ELIMINAR_VOLUNTARIO("ELIMINAR_VOLUNTARIO"),

    // Hogar
    CREAR_HOGAR("CREAR_HOGAR"),
    BUSCAR_HOGAR("BUSCAR_HOGAR"),
    MODIFICAR_HOGAR("MODIFICAR_HOGAR"),
    ELIMINAR_HOGAR("ELIMINAR_HOGAR"),
    
    CREAR_GATO("CREAR_GATOS"),
    MODIFICAR_GATO("MODIFICAR_GATOS"),
    VER_HISTORIAL("VER_HISTORIAL"),
    CREAR_DIAGNOSTICO("CREAR_DIAGNOSTICO"),
    POSTULARSE("POSTULARSE"),
    BUSCAR_FAMILIA_APTITUD("BUSCAR_FAMILIA_APTITUD"),
    BUSCAR_FAMILIA_ASIGNACION("BUSCAR_FAMILIA_ASIGNACION"),
    BUSCAR_HOGAR_APTITUD("BUSCAR_HOGAR_APTITUD"),
    BUSCAR_HOGAR_ASIGNACION("BUSCAR_HOGAR_ASIGNACION"),
    ASIGNAR_GATO_FAMILIA("ASIGNAR_GATO_FAMILIA"),
    ASIGNAR_GATO_HOGAR("ASIGNAR_GATO_HOGAR"),
    BUSCAR_VOLUNTARIO_TAREA_REALIZADA("BUSCAR_VOLUNTARIO_TAREA_REALIZADA"),
    TAREA_REALIZADA("TAREA_REALIZADA"),
    REPORTE("REPORTE");
    
    private final String texto;
    
    private PanelesAdministrador(String texto) {
        this.texto = texto;
    }
    
    public String getTexto() {
        return texto;
    }
}